server:
  port: 8989
  jsp-servlet:
    jsp:
      init-parameters:
        development: true
  servlet:
    context-path: /cmfz

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmfz
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  data:
    elasticsearch:
      cluster-nodes: 192.168.171.128:9300

mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:/mapper/*Mapper.xml